# PA 2 - NUMERICAL PYTHON (NUMPY) 
------

##### NO. 1 `NORMALIZATION PROBLEM`
------

In [26]:
import numpy as np

# GENERATES RANDOM 5 BY 5 NUMBERS
X = np.random.random((5,5))

# VISUALIZE EQUATION: Z = (X - mean) / σ)
X_normalized = (X - X.mean()) / X.std()

# SAVE NORMALIZED N-DIMENSIONAL ARRAY
np.save("X_normalized.npy", X_normalized)

print("   - Original X:\n", X) 
print("\n\n  - Normalized X:\n", X_normalized)


   - Original X:
 [[0.73857049 0.48012076 0.21504506 0.49840818 0.00226394]
 [0.92624076 0.4474504  0.55052147 0.73811061 0.36217763]
 [0.34046548 0.72673354 0.57508048 0.51293892 0.95824959]
 [0.37774951 0.97697731 0.59072494 0.70245627 0.62869884]
 [0.25008725 0.02123679 0.16490579 0.11942653 0.43786462]]


  - Normalized X:
 [[ 0.91219859 -0.05058659 -1.03805504  0.01753828 -1.83071404]
 [ 1.61131385 -0.17229127  0.21167239  0.91048542 -0.4899521 ]
 [-0.57083488  0.86810321  0.30316037  0.07166869  1.73055416]
 [-0.43194321  1.80031926  0.36143962  0.77766476  0.5029012 ]
 [-0.90751475 -1.76003576 -1.22483544 -1.39425623 -0.2080005 ]]


------
##### NO.2 `DIVISIBLE BY 3 PROBLEM`
------

In [6]:
import numpy as np

# CREATE 10 BY 10 N-DIMENSIONAL ARRAY 
A = np.arange(1, 101).reshape(10, 10) ** 2

# FIND ALL DIVISIBLE BY 3 FROM THE ARRAY
div_by_3 = A[A % 3 == 0]

# SAVE DIVISSIBLE BY 3 N-DIMENSIONAL ARRAY
np.save("div_by_3.npy", div_by_3)

print(" - Matrix A:\n", A)
print("\n - Elements Divisible by 3:\n", div_by_3)


 - Matrix A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

 - Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
